spring:
  application:
    name: rankingsystem
  jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
  rabbitmq:
      host: localhost
      port: 5672
      stomp:
          relay:
              host: 127.0.0.1
              port: 61613
              login: guest
              passcode: guest