# Standard Kafka Connector properties
name=file-stream-connector
connector.class=org.apache.kafka.connect.file.FileStreamSourceConnector
task.max=1

# Properties of Connecter
file=/temp/appendable-file.txt
topic=file-stream-connector
