bootstrap.servers=filestreamconnector-kafka-1:19092,filestreamconnector-kafka-2:19092

# Standalone => *.schemas.enable=false
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter.schemas.enable=false

rest.port=8086
rest.host.name=localhost
plugin.path=/usr/local/share/kafka/plugins,/usr/share/filestream-connectors

# Only for standalone workers
offset.storage.file.filename=standalone.offsets
offset.flush.interval.ms=10000